### PR TITLE
Refactor code

### PR DESCRIPTION
**Pull request by Shahor**
And fix object iteration

### CODE REVIEW

**Comment by arkxu** [comment]
I like this -adding promises. Could you help to do the following:

1. In the promise testing, adding 'reject' cases.
2. Complete the readme with the promises usage?

Thanks!

**Comment by Shahor** [comment]
Done

But I have to say that the tests currently have virtually no value (c.f. #8)

**Comment by arkxu** [comment]
nice, thanks!

**Comment by Shahor** [comment]
No problemo!

Could you publish those new changes on npm?

**Comment by arkxu** [comment]
just dit!

**Comment by Shahor** [comment]
Cool o/

**Pull request merged**
